version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Test-HL7"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3i40g32xdyl"
s3_prefix = "Test-HL7"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SourceBucketName=\"a-tester-testdohsrc\" DestinationBucketName=\"a-tester-testdohdes\""
