AWSTemplateFormatVersion: '2010-09-09'
Resources:
    PublicS3Bucket:
        Type: 'AWS::S3::Bucket'
        Properties:
            BucketName: !Sub 'public-s3-bucket-${AWS::AccountId}'
            AccessControl: PublicRead
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false
Outputs:
    BucketName:
        Description: Name of the S3 bucket
        Value: !Ref PublicS3Bucket