AWSTemplateFormatVersion: '2010-09-09'
Resources:
    PublicS3Bucket:
        Type: 'AWS::S3::Bucket'
        Properties:
            BucketName: !Sub 'public-s3-bucket-${AWS::AccountId}'
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                BlockPublicPolicy: false
                IgnorePublicAcls: false
                RestrictPublicBuckets: false
            WebsiteConfiguration:
                IndexDocument: index.html
    PublicS3BucketPolicy:
        Type: 'AWS::S3::BucketPolicy'
        Properties:
            Bucket: !Ref PublicS3Bucket
            PolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal: '*'
                      Action: 's3:GetObject'
                      Resource: !Sub '${PublicS3Bucket.Arn}/*'
Outputs:
    BucketName:
        Description: Name of the S3 bucket
        Value: !Ref PublicS3Bucket